# Generated by Django 3.0.6 on 2021-10-05 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211004_2200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friends',
        ),
    ]
